### ISSUE TITLE
New user confirmation with TML not working

### ISSUE THREAD

**Issue by nkeat12** [miled/wordpress-social-login#101]
User is auto signed in... No confirmation is required. 

Have tested with clean install and same issue.

**Comment by ftena** [comment]
It's working on installation. I followed the instructions here, section "3. Users Moderation":

http://miled.github.io/wordpress-social-login/bouncer.html

Since then, when a user connect with a social network, an email is sent to me and I need to approve the user in Wordpress. Otherwise, the user cannot connect to the site.
