### ISSUE TITLE
Facebook avatars are blank.

### ISSUE THREAD

**Issue by csrui** [miled/wordpress-social-login#117]
Maybe there was some update to facebook graph api, but the avatars are not displayed.

The url generated by the plugin is something like the url below but it ends redirected.

https://graph.facebook.com/10153976622758012/picture?width=150&height=150

When this is called in a img tag, it ends up with a 0 sized bytes response.

Anyone has this issue also?

**Comment by espellcaste** [comment]
I was just testing this and in my case, it loads the image, although I have the same url... Are you sure it is something with the plugin?

**Comment by phylaxis** [comment]
I'm having a different issue. I'm getting the avatar image, but also an error stating:

`Caught exception: String could not be parsed as XML`

**Comment by phylaxis** [comment]
I'm updating my own issue just in case someone else encounters this problem. In my case it turned out to be a conflict with the base theme I was using for development. I use [FoundationPress](https://foundationpress.olefredrik.com) and for some reason they have a `cleanup.php` library that has a filter on the `get_avatar_url()` function. That filter was conflicting with WP Social Login's Facebook avatar URLs. Not 100% sure why it's only Facebook. Regardless, I fixed it by commenting out the filter call in the FoundationPress library. I notified the FoundationPress developer and they have admitted that their 'cleanup' library needs a re-write.
