### ISSUE TITLE
Fix for the 406 Session Identifier Missing issue

### ISSUE THREAD

**Issue by mellinger** [miled/wordpress-social-login#201]
For people who are attempting to use this plugin in environments that don't support sticky sessions, this is how I got it to work...

1) Install and activate this plugin: https://wordpress.org/plugins/wp-native-php-sessions/
2) Include `$parse_uri = explode( 'wp-content', $_SERVER['SCRIPT_FILENAME'] );
require_once( $parse_uri[0] . 'wp-load.php' );` at the top of wordpress-social-login/hybridauth/index.php 

Hope this plugin gets updated soon!

**Comment by ollietreend** [comment]
Thanks for sharing this @mellinger! I'm having this exact same problem, and this post has been really helpful.

I'd already tried using the plugin [wp-native-php-sessions](https://wordpress.org/plugins/wp-native-php-sessions/), but it wasn't working. It makes sense now to realise that WordPress isn't actually loaded in those callbacks!

Have you put together a Pull Request for this to be merged into the plugin? Patching that file is going to be difficult since I'm using composer and [wpackagist](https://wpackagist.org/) to manage plugins.

**Comment by carollsdk** [comment]
Great contribution .. 
Helped me a lot, thank you.

**Comment by rvmourik** [comment]
Also hope this is added soon, very difficult to test social login on a local development server this way.

Thanks in advance.

**Comment by moahammadalt** [comment]
what if I am not able to log in as an admin to download this plugin, any solution, please?

**Comment by AUCoinonline** [comment]
You are the best, this works too super well, only place I could fine a lasting solution.

**Comment by SumeetGohil** [comment]
I have been trying to resolve this for almost 3 weeks this saves my ass :D
