### ISSUE TITLE
redirect_url must be absolute

### ISSUE THREAD

**Issue by Tusko** [miled/wordpress-social-login#44]
Hi guys) after update to v 2.2.2 I have error like "The redirect_uri URL must be absolute". can you fix it?

**Comment by knicklabs** [comment]
I'm using the latest version of the plugin and this is still an issue. At least Google and Facebook require an absolute path, including protocol for the URL redirect. The plugin URL defined in this plugin is a relative path. Sure, the path can be redefined, but it shouldn't need to be. If it does, it should be noted in the docs. Not sure why this issue was closed.
