### ISSUE TITLE
Twitter, can't merge with existing account using existing email

### ISSUE THREAD

**Issue by ihorvorotnov** [miled/wordpress-social-login#87]
I already have a native WP account on the site, trying to log in to the site via Twitter. Twitter is not giving the email, so WSL Bouncer asks for my email. I enter the same email that's in use by my native WP login and get an error 'This email is already registered' instead of expected account merge. Facebook and Google worked as expected.

![screencapture-famous-dev-core-wp-login-php-1431689098712](https://cloud.githubusercontent.com/assets/1066083/7651884/579a8ab6-fb0e-11e4-8d8b-3e91c7c0c1d8.png)

**Comment by miled** [comment]
Yes, that's an expected behavior. WSL doesn't allow that for security reasons to prevent identity theft and privilege escalation: You may imagine the case where someone knows your admin email, then he can easily signup with a fake twitter account and merge it using your email granting himself absolute power over the website.

To solve this use case, a new feature is planned to allow users to [link their social accounts](https://github.com/miled/wordpress-social-login/blob/master/includes/services/wsl.authentication.php#L446-L462) after authenticating themselves.

**Comment by ihorvorotnov** [comment]
Thanks for clarification, haven't thought about possible theft in that way, sounds reasonable. Linking social network accounts to already existing profile is exactly what I'm looking for.
